Site V2
jaspermayone/website pull request #26
Opened 2024-08-01 15:33 UTC by jaspermayone

2024-09-15 04:17 UTC, aramshiva requested changes

2024-09-15 04:17 UTC, aramshiva commented on src/pages/_app.tsx
>        <Component {...pageProps} />
```suggestion
      <AnimatePresence>
      <Component {...pageProps} />
      </AnimatePresence>
```

2024-09-15 04:17 UTC, aramshiva commented on src/pages/_app.tsx
> +import Head from "next/head";
```suggestion
import Head from "next/head";
import AnimatePresence from "framer-motion";
```

2024-09-15 04:43 UTC, aramshiva commented
What’s the error in logs?

> On Sep 14, 2024, at 9:26 PM, Jasper Mayone ***@***.***> wrote:
> 
> 
> oh dear its unhappy now @aramshiva <https://github.com/aramshiva>
> —
> Reply to this email directly, view it on GitHub <https://github.com/jaspermayone/website/pull/26#issuecomment-2351358436>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AS6MJBCF4LYQXIN4QRTJ2ETZWUD7XAVCNFSM6AAAAABL22FHGSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNJRGM2TQNBTGY>.
> You are receiving this because you were mentioned.
>

2024-09-15 13:05 UTC, jaspermayone commented
@aramshiva 
![CleanShot 2024-09-15 at 09 04 34@2x](https://github.com/user-attachments/assets/264d7bac-d0d9-4c88-8924-55cd1a900be9)
![CleanShot 2024-09-15 at 09 05 15@2x](https://github.com/user-attachments/assets/cd3cc17d-674b-49ce-8d0d-7eecb12c8f1c)

2024-09-15 13:06 UTC, jaspermayone commented
![CleanShot 2024-09-15 at 09 05 45@2x](https://github.com/user-attachments/assets/b5ab6a35-0578-4dd4-9a70-def71f5dc112)
its complaining about animate presence in the app.ts

2024-09-15 13:07 UTC, jaspermayone commented
I fixed it, but am still getting keyframe errors.

2024-09-17 00:19 UTC, jaspermayone commented
World's most insane PR right here :)

2024-09-17 13:02 UTC, jaspermayone commented
@aramshiva I made a new "gallery" type view on /friends for something I am working on, but the files won't be numbered like the photo gallery on my photo page for the v1 site. I am storing the images in a folder, is there any way we can adapt the api to work for that?

2024-09-17 14:22 UTC, aramshiva commented
i dont think it needs to be numbered

2024-09-17 16:10 UTC, jaspermayone commented
Is there a way to loop through the files in a folder or should I do them individually?

2024-09-19 17:01 UTC, jaspermayone commented
@aramshiva can you look at [88e0a4e](https://github.com/jaspermayone/website/pull/26/commits/88e0a4e59dbbd8506bb981dfc3895f91e9078c8c) please? The /friends page seems to be loading in images in a weird way... it might just be the number of images, but one side seems to lack images down towards the bottom.

2024-09-19 22:12 UTC, aramshiva commented
> @aramshiva can you look at [88e0a4e](https://github.com/jaspermayone/website/pull/26/commits/88e0a4e59dbbd8506bb981dfc3895f91e9078c8c) please? The /friends page seems to be loading in images in a weird way... it might just be the number of images, but one side seems to lack images down towards the bottom.

You can have the Image with a [Suspense](https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming) or change the [Priority](https://nextjs.org/docs/pages/building-your-application/optimizing/images#priority)

2024-09-20 00:06 UTC, jaspermayone commented
Perfect! Ty!

2024-09-20 21:23 UTC, jaspermayone commented
MERGE TIMEEEE

2024-09-20 21:24 UTC, merged